repos:
  - repo: 'https://github.com/igorshubovych/markdownlint-cli'
    rev: v0.42.0
    hooks:
      - id: markdownlint
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v1.61.0
    hooks:
      - id: golangci-lint
