repos:
  - repo: 'https://github.com/igorshubovych/markdownlint-cli'
    rev: v0.28.1
    hooks:
      - id: markdownlint
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v1.42.1
    hooks:
      - id: golangci-lint
